---
title: "2_DataExploration"
author: "Simon Topp"
date: "2/3/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(googledrive)
library(sf)
library(mapview)

knitr::opts_chunk$set(echo = TRUE)
```

# First, take a look at overall hydrscape variables, riverine, non-riverine, and centerline length

```{r}
drive_download('MdD_Exports/MdD_Hydroscape_TS_DL_Riv_Global.csv', 'out/MdD_Hydroscape_TS_DL_Riv_Global.csv', overwrite = T)

basins.sf <- st_read('D:/GIS_Data/HydroSheds/hybas_sa_lev08_v1c.shp') %>%
  filter(HYBAS_ID %in% c(6080540660, 6080548660,6080540560,6080549240,6080549470,6080548950,6080552360,6080552360,6080552520, 6080546500))

mapView(basins.sf)

hsFull <- read_csv('out/MdD_Hydroscape_TS_DL_Riv_Global.csv') %>% 
  bind_rows(read_csv('out/MdD_Hydroscape_TS_DL_Riv_Guyana.csv')) %>%
  select(-`system:index`, - .geo) %>%
  spread(feature, area) %>%
  mutate(nonRivArea = waterArea - rivArea) %>%
  gather('feature', 'area', cl, rivArea, waterArea, nonRivArea) %>%
  mutate(Basin = ifelse(BasinID == 6080540660, 'Upstream Manu', 
                        ifelse(BasinID == 6080548660, 'Reserve',
                               ifelse(BasinID == 6080540560, 'UpstreamManuNorth',
                                ifelse(BasinID == 6080549240, 'Manu - Co.',
                                  ifelse(BasinID == 6080549470, 'Colorado',
                                   ifelse(BasinID == 6080548950, 'Co.- In. West',
                                      ifelse(BasinID == 6080552360, 'Co.- In. East',
                                        ifelse(BasinID == 6080552520, 'Inambari',
                                         ifelse(BasinID == 1080982910, 'G_OffinSouth', 
                                          ifelse(BasinID == 1080977020, 'Offin River, Ghana', 
                                          ifelse(BasinID == 1081012470, 'G_Ankobra',
                                            ifelse(BasinID == 6080108730, 'Rio Quito, Colombia',
                                             ifelse(BasinID == 5080162350, 'Kahayan River, Indonesia',
                                              ifelse(BasinID == 5080166880, 'I_Kapuas',
                                                ifelse(BasinID == 6080546500, 'In.- Puerto', 
                                                  ifelse(BasinID == 6080099320, 'Guyana', NA)))))))))))))))),
         area.km = area/1000000) %>%
  group_by(BasinID, Basin, feature) %>%
  mutate(area.percent = scale(area, scale = mean(area)) + 1,
         diff = c(NA, diff(area.percent))) %>%
  ungroup() 

## For now just filter to Peru Area
hsPeru <- hsFull %>% filter(BasinID %in% c(6080540660, 6080548660,6080549240,6080549470,6080548950,6080552360,6080552360,6080552520, 6080546500))#,6080540560

##Basic change over time
ggplot(hsPeru %>% filter(!feature %in% c('cl', 'waterArea')), aes(x = year, y = area.percent, color = feature)) + 
  geom_point(alpha = .4) + 
  geom_smooth(se = F, span = .2) + 
  scale_color_viridis_d(end = .6, labels = c('Lentic', 'Lotic')) +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~Basin, nrow = 2) +
  theme_bw() +
  labs(x = 'Year', y = 'Area (% of mean)', color = 'Type', title = 'Change in Surface water extent') +
  theme(legend.position = 'bottom')

ggsave('figures/LenLot.pdf', width = 6.5, height = 3, units = 'in')

hsPeru %>% select(feature, year, Basin, diff) %>%
  spread(feature, diff) %>%
  ggplot(., aes(x = cl, y = rivArea, color = year)) +
  geom_point() + 
  geom_abline(color = 'red') +
  scale_color_viridis_c(end = .8) +
  facet_wrap(~Basin, scales='free') +
  theme_bw() +
  labs(y = expression(paste(Delta,' River Area')), x =expression(paste(Delta, ' Centerline Length')), title = 'Centerline length vs river area')


## Take a look at Sinuosity.  The distances in the distance var are pulled out of google earth and are just
## the distance as the bird flies from the start to the end of each channel for each basin.

##Birds eye distances by watersehed
distances = tibble(Basin = unique(hs$Basin), EucDist = c(14200, 84101, 60684, 24720, 36577, 67224+18383+7005, 55659+53012+19625, 39543, 87737))

hs %>% filter(feature == 'cl') %>%
  left_join(distances) %>%
  mutate(sinuosity = EucDist/(area*30)) %>%
  ggplot(., aes(x = year, y = sinuosity)) +
  geom_point(alpha = .4) + 
  geom_smooth(se = F, span = .2) + 
  facet_wrap(~Basin) +
  theme_bw()


ggplot(hsPeru %>% filter(!feature %in% c('cl', 'waterArea')), aes(x = year, y = area.km, color = feature)) + 
  geom_point(alpha = .4) +
  scale_color_discrete(labels = c('Non-River Water Area', 'Riverine Water Area')) +
  geom_smooth(se = F) + 
  facet_wrap(~Basin, scales='free') +
  labs(x = 'Year', y = 'Centered Area (sq. km)', color = 'Area Type') +
  theme_bw()



## Quickly look at centerline length
hsPeru %>% filter(feature == 'cl') %>% 
  ggplot(., aes(x = year, y = area.percent)) + geom_line() + facet_wrap(~Basin)


hsPeru %>% mutate(period = ifelse(year < 1990, 'start', ifelse(year > 2013, 'end', NA))) %>%
  filter(!is.na(period),
          feature == 'nonRivArea') %>%
  select(Basin, period, feature, area.km) %>%
  group_by(Basin, period, feature) %>%
  summarise(area.km = mean(area.km)) %>%
  spread(period, area.km) %>%
  mutate(dif = start - end,
         mined = ifelse(Basin %in% c('Colorado', 'Inambari'), T, F)) %>%
  group_by(mined) %>% summarise(meanDif = mean(dif))


hsPeru %>% mutate(period = ifelse(year == 1985, 'start', ifelse(year == 2018, 'end', NA))) %>%
  filter(!is.na(period),
          feature == 'rivArea') %>%
  select(Basin, period, feature, area.km) %>%
  group_by(Basin, period, feature) %>%
  summarise(area.km = mean(area.km)) %>%
  spread(period, area.km) %>%
  mutate(dif = start - end) %>%
    


## Get cumulative areas for downstream lotic/lentic systems
hsPeru %>%
  filter(!Basin %in% c('Upstream Manu', 'Manu - Co.', 'Reserve'),
         year %in% c(1985,2018),
         feature  %in% c('rivArea', 'nonRivArea')) %>%
  group_by(year, feature) %>%
  summarise(sum = sum(area.km)) %>%
  spread(year, sum) %>%
  mutate(diff = `2018` - `1985`,
         prop = `2018`/`1985`)
```

## Check out Erosion and Accretion

```{r}
##Check out erosion and accretion real quick
drive_download('MdD_Exports/MdD_ErosAcrec_DL_Riv.csv', 'out/MdD_ErosAcrec_DL_Riv.csv', overwrite = T)

ea <- read.csv('out/MdD_ErosAcrec_DL_Riv.csv') %>%
  mutate(Basin = ifelse(BasinID == 6080540660, 'UpStreamManuSouth', 
                        ifelse(BasinID == 6080548660, 'Reserva',
                               ifelse(BasinID == 6080540560, 'UpstreamManuNorth',
                                      ifelse(BasinID == 6080549240, 'Manu_Colorado',
                                             ifelse(BasinID == 6080549470, 'Colorado',
                                                    ifelse(BasinID == 6080548950, 'Colorado_InamWest',
                                                           ifelse(BasinID == 6080552360, 'Colorado_InamEast',
                                                              ifelse(BasinID == 6080552360, 'Colorado_InamEast',
                                                                     ifelse(BasinID == 6080552520, 'Inambari','Inam_Puerto'))))))))),
         area.km = area/1000000) %>%
  group_by(BasinID, Basin, feature) %>%
  mutate(area.percent = scale(area, scale = mean(area)),
         diff = c(NA, diff(area.percent))) %>%
  ungroup()


ggplot(ea %>% filter(feature == 'AccretionArea'), aes(x = year, y = area.percent)) + 
  #geom_point(alpha = .4) + 
  geom_line() +
  geom_smooth(method = 'lm') +
  theme_bw() +
  facet_wrap(~Basin, scales = 'free_y') +
  labs(x = 'Year', y = 'Scaled Erosion Rate (Erosion/Mean Erosion)', title = 'Erosion by watershed over time')


eaDiff <- ea %>%
  select(Basin, area.percent, feature, year) %>%
  spread(feature, area.percent) %>%
  mutate(AreaChange = AccretionArea - ErosionArea)

eaDiff %>%
  ggplot(., aes(x= year, y = AreaChange)) + geom_line() + geom_smooth(method = 'lm') + facet_wrap(~Basin) 
```


```{r}
## Check out the cocha Areas
drive_download('MdD_Exports/Cocha_Areas_CutOff.csv', 'out/Cocha_Areas_CutOff.csv')

cochaIDs <- read.csv('in/Cocha_Pond_Cords_Full.csv')

cochas <- read.csv('out/Cocha_Areas_CutOff.csv') %>%
  select(Unique_ID, year, area) %>%
  left_join(cochaIDs) %>%
  mutate(con2018 = ifelse(Unique_ID %in% c(3,4,5,8,9,15), T, F)) %>% mutate(version = 'Cut')


cochas.sf <- cochas %>% filter(Type == 'cocha') %>% st_as_sf(coords = c('Long', 'Lat'), crs = 4326)

mapView(cochas.sf, zcol = factor('Unique_ID'))

ggplot(cochas %>% filter(Type == 'cocha', version == 'Cut'), aes(x = year, y = area/1000000, color = con2018)) + geom_line() + 
  #geom_hline(yintercept = 1500000) + 
  facet_wrap(~Unique_ID, scales = 'free')

max(cochas$area)
hist(cochas$area)

#For jackie

out <- read.csv('out/Cocha_Areas_CutOff.csv') %>%
  select(Unique_ID, year, area) %>%
  left_join(cochaIDs) %>%
  mutate(Connectivity_2018 = ifelse(Unique_ID %in% c(3,4,5,8,9,15), T, F))

write_csv(out, 'out/CochaAreas.csv')
```

##Forested areas

```{r}
drive_download('MdD_Exports/MdD_CochaDeforestation_RivRemoved.csv', 'out/CochaDeforestation_RivRemoved.csv')
drive_download('MdD_Exports/MdD_BasinDeforestation_RivRemoved.csv', 'out/Basin_Deforestation_RivRemoved.csv')

cochas <- read.csv('out/CochaDeforestation_RivRemoved.csv') %>%
  gather(ForestToWater, ForestToBarren, key = 'feature', value = 'area') %>%
  select(Unique_ID, feature, year, area) %>%
  mutate(area.km = area/1000000) %>%
  group_by(feature, Unique_ID) %>%
  #arrange(year) %>%
  mutate(cumulative = cumsum(area.km)) %>%
  ungroup()

ggplot(cochas, aes(x = year, y = area.km, fill = feature)) + geom_col() + facet_wrap(~Unique_ID) + labs(x = 'year', y = 'Forest loss (sq km)', title = 'Forest loss within 2km of Cocha')
ggplot(cochas, aes(x = year, y = cumulative, fill = feature)) + geom_col() + facet_wrap(~Unique_ID) + labs(x = 'year', y = 'Cumulative Forest loss (sq km)', title = 'Cumulative Forest loss within 2km of Cocha')


basin <- read.csv('out/Basin_Deforestation_RivRemoved.csv') %>%
  select(BasinID, year, area, feature) %>%
  mutate(Basin = ifelse(BasinID == 6080540660, 'Upstream Manu', 
                        ifelse(BasinID == 6080548660, 'Reserve',
                               ifelse(BasinID == 6080540560, 'UpstreamManuNorth',
                                ifelse(BasinID == 6080549240, 'Manu - Co.',
                                  ifelse(BasinID == 6080549470, 'Colorado',
                                   ifelse(BasinID == 6080548950, 'Co.- In. West',
                                      ifelse(BasinID == 6080552360, 'Co.- In. East',
                                        ifelse(BasinID == 6080552520, 'Inambari','In.- Puerto')))))))),
         area.km = area/1000000) %>%
  group_by(BasinID, Basin, feature) %>%
  mutate(cumulative = cumsum(area.km)) %>%
  ungroup() %>% filter(Basin != 'UpstreamManuNorth')

sum(basin$cumulative[basin$year == 2018])

ggplot(basin, aes(x = year, y = area.km, fill = feature)) + geom_col() + facet_wrap(~Basin) + labs(x = 'year', y = 'Forest loss (sq km)', title = 'Forest loss within the Basin')


p1 <- ggplot(basin %>% filter(feature == 'ForestToBarren'), 
       aes(x = year, y = cumulative)) + 
  geom_col(fill = '#5d4235') + 
  facet_wrap(~Basin, ncol = 1) + 
  theme_bw() +
  theme(axis.title =element_blank())

p2 <- ggplot(basin %>% filter(feature == 'ForestToWater'), 
       aes(x = year, y = cumulative)) + 
  geom_col(fill = '#1e96a6') + 
  facet_wrap(~Basin, ncol = 1) + 
  theme_bw() +
  theme(axis.title = element_blank())

leg <- cowplot::get_legend(ggplot(basin, aes(x = year, y = cumulative)) + 
  geom_col(aes(fill = feature)) +
  scale_fill_manual('Conversion\nType', values = c('#5d4235','#1e96a6'), labels = c('To Barren', 'To Water'))) 

g <- gridExtra::grid.arrange(p1, p2, leg, ncol = 3, widths = c(1,1,.5), left = 'Cumulative Forest Loss (sq. km.)', bottom = 'Year', top = 'Forest Loss by Watershed') 

ggsave('out/cumForestLoss.png', g, height = 8, width = 5, units = 'in')

PropConv <- basin %>% filter(year == 2018) %>%
  select(Basin, cumulative, feature) %>%
  spread(feature, cumulative) %>%
  mutate(proportion = ForestToWater/ForestToBarren) %>% mutate(mined = ifelse(Basin %in% c('Colorado', 'Inambari'), T, F))

PropConv %>% group_by(mined) %>% summarise(mean = mean(proportion))

Prop <- basin %>% filter(year == 2018) %>%
  group_by(feature) %>%
  summarise(sum = sum(cumulative))

  select(Basin, cumulative, feature) %>%
  spread(feature, cumulative) %>%
  mutate(proportion = ForestToWater/ForestToBarren) %>% mutate(mined = ifelse(Basin %in% c('Colorado', 'Inambari'), T, F))

p1 <- ggplot(cochas %>% filter(feature == 'ForestToBarren'), 
       aes(x = year, y = cumulative)) + 
  geom_col(fill = '#5d4235') + 
  facet_wrap(~Unique_ID, ncol = 2) + 
  theme_bw() +
  theme(axis.title =element_blank())

p2 <- ggplot(cochas %>% filter(feature == 'ForestToWater'), 
       aes(x = year, y = cumulative)) + 
  geom_col(fill = '#1e96a6') + 
  facet_wrap(~Unique_ID, ncol = 2) + 
  theme_bw() +
  theme(axis.title = element_blank())

leg <- cowplot::get_legend(ggplot(basin, aes(x = year, y = cumulative)) + 
  geom_col(aes(fill = feature)) +
  scale_fill_manual('Conversion\nType', values = c('#5d4235','#1e96a6'), labels = c('To Barren', 'To Water'))) 

g <- gridExtra::grid.arrange(p1, p2, leg, ncol = 3, widths = c(1,1,.5), left = 'Cumulative Forest Loss (sq. km.)', bottom = 'Year', top = 'Forest Loss by Watershed') 

ggsave('out/cumForestLoss.png', g, height = 8, width = 5, units = 'in')


```


```{r}
## Pull lat/long out of the caster data.
files <- list.files('in/CasterData', full.names = T)

for(i in files){
  if(i == files[1]){
    file <- read.csv(i)
    lat <- as.numeric(as.character(file[,2][file$X..Device == '% Start latitude']))
    long <- as.numeric(as.character(file[,2][file$X..Device == '% Start longitude']))
    locations = tibble(lat = lat, long = long)
  } else{
    file <- read.csv(i)
    lat <- as.numeric(as.character(file[,2][file$X..Device == '% Start latitude']))
    long <- as.numeric(as.character(file[,2][file$X..Device == '% Start longitude']))
    locations = locations %>% bind_rows(tibble(lat = lat, long = long))
  }
}


caster = locations %>% na.omit() %>% mutate(source = 'caster', Date = NA, Time = NA, Site.Name = NA, Type = NA, Unique_ID = -99) %>% st_as_sf(coords = c('long', 'lat'), crs = 4326)
ogLocs <- read.csv('in/Cocha_Pond_Cords_Full.csv') %>% st_as_sf(coords = c('Long', 'Lat'), crs = 4326) %>% mutate(source = 'original')
newLocs <- st_read('in/PondCenterpointsFull.shp') %>% mutate(source = 'relocated') %>% select(-c(Lat, Long)) %>% rename(Site.Name = Site_Name)

locs <- ogLocs %>% rbind(newLocs)  %>% filter(Unique_ID %in% c(5, -99)) %>% mutate(source = factor(source, levels = c('original', 'relocated')))
mapview(locs, zcol = 'source')
?mapview
#%>% rbind(caster)

```


```{r}

## Put together a csv to send up to EE for charting
forestOut <- basin %>% select(BasinID, year, cumulative, feature) %>%
  spread(feature, cumulative) %>%
  mutate(area = ForestToBarren + ForestToWater,
         feature = 'cum.defor',
         area.percent = -999) %>%
  select(BasinID, year, area, feature, area.percent)

areasOut <- hs %>%
  select(BasinID, year, area = area.km, feature, area.percent) %>%
  filter(feature %in% c('rivArea', 'nonRivArea')) %>%
  bind_rows(forestOut) %>%
  mutate(area.percent = (area.percent + 1))

ggplot(areasOut %>% filter(feature == 'nonRivArea'), aes(x = year, y = area.percent)) +geom_line() +facet_wrap(~BasinID, scales = 'free')
colSums(is.na(areasOut))
write_csv(areasOut, 'out/EEChartAreas.csv')
```



```{r}
## Try to make a legend stand alone legend

dummy = tibble(Year = seq(1985,2018,1), pnts = 1)

p <- ggplot(dummy, aes(x = Year, y = pnts, color = Year)) + geom_point() +
  scale_color_viridis_c(begin = .3) +
  theme(legend.position = 'bottom',
        legend.title.align = 0,
        legend.title = element_text(vjust = .75))
p
ggsave('out/dummyLegend.pdf')

cowplot::get_legend(p)

##Messing around with visualizing exported GeoTiff
colombiaStack <- raster::raster('out/WaterStack_Colombia.tif')
ghanaStack <- raster::raster('out/WaterStack_Ghana.tif')
indonesiaStack <- raster::raster('out/WaterStack_Indonesia.tif')
peruStack <- raster::raster('out/WaterStack_Peru.tif')

##Make Subset for Other countries:
hsGlob = hsFull %>% filter(BasinID %in% c(6080108730, 1080977020, 5080162350, 6080099320))

ggplot(hsGlob %>% filter(!feature %in% c('cl', 'waterArea')), aes(x = year, y = area.percent, color = feature)) + 
  geom_point(alpha = .4) + 
  geom_smooth(se = F, span = .2) + 
  scale_color_viridis_d(end = .6, labels = c('Lentic', 'Lotic')) +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~Basin, nrow = 3) +
  theme_bw() +
  labs(x = 'Year', y = 'Area (% of mean)', color = 'Type', title = 'Change in Surface water extent') +
  theme(legend.position = 'bottom')

ggsave('figures/LenLotGlobal.pdf', width = 2.5, height = 7, units = 'in')

library(rasterVis)

rasterVis::gplot(colombiaStack, maxpixels = 5e5) + 
  geom_raster(aes(fill = value), interpolate = T) +
  scale_fill_viridis_c('Year', na.value = 'black', begin = .3) +
  coord_equal() +
  theme_void() +
  ylim(c(5.3, 5.6)) +
  xlim(c(-76.8, -76.6)) +
  labs(x = 'Longitude', y = 'Latitude') + 
  theme(legend.position = 'none',
        axis.title.x = element_blank())

ggsave('figures/ColombiaStack.png', height = 1.85, width = 2, units = 'in')

rasterVis::gplot(ghanaStack, maxpixels = 5e5) + 
  geom_raster(aes(fill = value), interpolate = T) +
  scale_fill_viridis_c('Year', na.value = 'black', begin = .3) +
  coord_equal() +
  theme_void()  +
  ylim(c(6.1, 6.55)) +
  xlim(c(-2.1, -1.95)) +
  labs(x = 'Longitude', y = 'Latitude') + 
  theme(legend.position = 'none',
        axis.title.x = element_blank())
ggsave('figures/ghanaStack.png', height = 1.85, width = 2, units = 'in')

rasterVis::gplot(indonesiaStack, maxpixels = 5e5) + 
  geom_raster(aes(fill = value), interpolate = T) +
  scale_fill_viridis_c('Year', na.value = 'black', begin = .3) +
  coord_equal() +
  theme_void() +
  ylim(c(-1.5, -1.1)) +
  #xlim(c(111.38, 111.4)) +
  labs(x = 'Longitude', y = '') + 
  theme(legend.position = 'none')

ggsave('figures/indonesiaStack.png', height = 1.85, width = 2, units = 'in')


bounds <- tibble(lon = c(-71.4878, -69.120307), lat = c(-13.1649, -12.2164))
bb <- make_bbox(lon, lat, data = bounds)
calc_zoom(bb)

## Programatically make figure 1
sq_map <- ggmap::get_map(location = c(lon = -70.3733, lat = -12.6302), zoom = 9, source = 'google', maptype = "satellite")

stack <-  ggR(peruStack %>% raster::aggregate(., fact = 2), ggObj = FALSE) %>%
  na.omit() %>%
  rename(lon = x, lat = y)

ggmap(sq_map) + geom_tile(data = stack, aes(x = lon, y = lat, fill = value)) +
  geom_sf(data = basins.sf %>% st_transform(crs = 4326), inherit.aes = F, fill = 'transparent') + 
  #scale_color_manual('Basins', values = c('blue', 'red'), breaks = c(1,2)) +
  scale_fill_viridis_c('Year', begin = .3)
```

## Look at trends

```{r}
lmKm <- hsPeru %>% filter(feature %in% c('rivArea', 'nonRivArea')) %>%
  group_by(feature, Basin) %>%
  nest() %>%
  mutate(lm = map(data, ~lm(area.km~year, .)),
         tidy = map(lm, broom::tidy))  %>%
  unnest(tidy) %>%
  filter(term == 'year') %>%
  arrange(feature, estimate) %>%
  mutate(area = 'km') %>% 
  bind_rows(hsPeru %>% filter(feature %in% c('rivArea', 'nonRivArea')) %>%
  group_by(feature, Basin) %>%
  nest() %>%
  mutate(lm = map(data, ~lm(area.percent ~ year, .)),
         tidy = map(lm, broom::tidy))%>%
  unnest(tidy) %>%
  filter(term == 'year') %>%
  arrange(feature, estimate) %>% mutate(area = 'percent')) %>% 
  mutate(Mined = ifelse(Basin %in% c('Colorado', 'Inambari'), T, F))

lmAves <- lmKm %>% group_by(feature, area, Mined) %>% summarise(mean = mean(estimate), sd = sd(estimate), median = median(estimate))

anova(lmKm$lm[lmKm$feature == 'nonRivArea' & is.na(lmKm$area)][[1]])
aov <- aov(lmKm$lm[lmKm$feature == 'nonRivArea' & is.na(lmKm$area)][[1]])
tukes <- TukeyHSD(aov, 'Basin')



```

