---
title: "2_HgAnalysis"
author: "Jackie Gerson"
date: "3/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

#This file reads in and analyzes mercury data in surface waters for Madre de Dios, Peru.

```{r cars}
#Read in data files and combine into one dataframe
oxbow.all<-read.csv("in/Oxbow.lake.data.csv")
mining.pond.all<-read.csv("in/Mining.pond.data.csv")
river.all<-read.csv("in/River.data.csv")

river.all.subset<-river.all[,c("Site.number","Site.type","Collection.date","Collection.time","Lat","Long","TSS.mg.L","Percent.C.sed","Ave.THg.sed.ug.g","THg.water.ng.L","MeHg.water.ng.L","Percent.MeHg.water")]

## Update the oxbow lake/mining pond coordinates with the centerpoints pulled from EE
## This is just because some of the sample points were on the edges and for analysis we
## need centerpoints.
oxbowCenters <- read.csv('in/LenticCenterPoints.csv')

oxbow.all <- oxbow.all %>% select(-Lat, -Long) %>%
  left_join(oxbowCenters %>% select(Collection.date = Date, Collection.time = Time, Lat, Long))

oxbow.mining.all<-rbind(oxbow.all,mining.pond.all)


## English Labels
water.labels <- c("River Upstream", "Oxbow Upstream", "Mining Pond", "River Downstream", "Oxbow Downstream")
fig.labels <- c("River\nUpstream","Oxbow\nUpstream","Mining\nPond","River\nDownstream","Oxbow\nDownstream")

## Make Alternate labels for Spanish Version
water.labels <- c("Río Arriba", "Lagos de Meandros Río Arriba", "Pozas de Minero", "Río Abajo", "Lagos de Meandros Río Abajo")
fig.labels <- c("Río Arriba","Lagos de Meandros\nRío Arriba","Pozas de\nMinero","Río Abajo", "Lagos de Meandros\nRío Abajo")

## Finally alternate labels for briefing
water.labels <- c("River Upstream", "Lake Upstream", "Mining Pond", "River Downstream", "Lake Downstream")
fig.labels <- c("River\nUpstream","Oxbow\nUpstream","Mining\nPond","River\nDownstream","Oxbow\nDownstream")

water.all<-rbind(oxbow.mining.all,river.all.subset) %>%
  mutate(Site.type = factor(Site.type, levels = c("river.upstream", "oxbow.lake.upstream", "mining.pond", "river.downstream", "oxbow.lake.downstream"), labels = water.labels))
```

## Make some figures

```{r cars}
#Create boxplots to compare Hg concentrations across surface water types
cb <- c("#56B4E9","#E69F00","#999999","#0072B2","#D55E00")

## Total Hg
tukeyThg <- tibble(Site.type = water.labels, TukeyStats = c('a','a','ab','b','a'))

g1<-ggplot(water.all,aes(x=Site.type, y=THg.water.ng.L)) + 
  geom_boxplot(aes(fill=Site.type)) +
  geom_label(data = tukeyThg, aes(y = Inf, label = TukeyStats), vjust = 2, label.size = .2) +
  #labs(x="",y="THg (ng/L)") + 
  labs(x="",y="HgT (ng/L)") + 
  scale_y_continuous(trans = 'log10') +
  theme_bw() + 
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        legend.position="top") + 
  scale_fill_manual(values=cb) + 
  labs(fill="") 


## MeHg
tukeyMeHg <- tibble(Site.type = water.labels, TukeyStats = c('a','ab','b','b','b'))
  
g2<-ggplot(water.all,aes(x=Site.type, y=MeHg.water.ng.L)) + 
  geom_boxplot(aes(fill=Site.type)) +
  geom_label(data = tukeyMeHg, aes(y = Inf, label = TukeyStats), vjust = 2, label.size = .2) +
  theme_bw()+
  labs(y="MeHg (ng/L)")+
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        legend.position="none") +
  scale_fill_manual(values=cb)

## Percent MeHg

tukeyPMeHg <- tibble(Site.type = water.labels, TukeyStats = c('a','a','a','b','a'))

g3<-ggplot(water.all,aes(x=Site.type, y=Percent.MeHg.water)) + 
  geom_boxplot(aes(fill=Site.type)) +
  geom_label(data = tukeyPMeHg, aes(y = Inf, label = TukeyStats), vjust = 2, label.size = .2) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 27, hjust = 1),
        axis.title.x = element_blank()) +
  #labs(y="Percent Hg\nas MeHg")+
  labs(y = 'Porcentaje de\nHg como MeHg') +
  scale_fill_manual(values=cb) +
  scale_x_discrete(labels=fig.labels)

## Average Sediment THg

tukeySTHg <- tibble(Site.type = water.labels, TukeyStats = c('a','ab','ab','a','b'))

g4 <- ggplot(water.all,aes(x=Site.type, y=Ave.THg.sed.ug.g)) + 
  geom_boxplot(aes(fill=Site.type)) +
  geom_label(data = tukeySTHg, aes(y = Inf, label = TukeyStats), vjust = 2, label.size = .2) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 27, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y="Sedimento HgT\n(ug/g)") +
  #labs(y="Sedimento THg\n(ug/g)") +
  scale_x_discrete(labels=fig.labels)+
  scale_y_continuous(trans = 'log10') +
  scale_fill_manual(values=cb, labels = fig.labels) +
  theme(legend.position="top") +
  labs(fill="")

tukeyTSS <- tibble(Site.type = water.labels, TukeyStats = c('ab','a','ab','c','b'))

g5 <- ggplot(water.all,aes(x=Site.type, y=TSS.mg.L)) + 
  geom_boxplot(aes(fill=Site.type)) +
  geom_label(data = tukeyTSS, aes(y = Inf, label = TukeyStats), vjust = 2, label.size = .2) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 27, hjust = 1),
        axis.title.x = element_blank()) +
  #labs(y="TSS (mg/L)") +
  labs(y="SST (mg/L)") +
  scale_x_discrete(labels=fig.labels)+
  scale_fill_manual(values=cb) +
  theme(legend.position="top") +
  labs(fill="")

#Create frequency distributions to compare Hg concentrations across surface water types
water.all.THg<-water.all[order(-water.all$THg.water.ng.L),]
water.all.THg$ID<-seq.int(nrow(water.all.THg))
water.all.MeHg<-water.all[order(-water.all$MeHg.water.ng.L),]
water.all.MeHg$ID<-seq.int(nrow(water.all.MeHg))
water.all.Percent<-water.all[order(-water.all$Percent.MeHg.water),]
water.all.Percent$ID<-seq.int(nrow(water.all.Percent))
water.all.THg.sed<-water.all[order(-water.all$Ave.THg.sed.ug.g),]
water.all.THg.sed$ID<-seq.int(nrow(water.all.THg.sed))
water.all.THg.TSS<-water.all[order(-water.all$TSS.mg.L),]
water.all.THg.TSS$ID<-seq.int(nrow(water.all.THg.TSS))

#Total Hg
gg1<-ggplot(water.all.THg, aes(x=ID, y=THg.water.ng.L, fill=Site.type))+
  geom_bar(stat="identity")+
  theme_bw() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="none",
        axis.title = element_blank())+
  labs(fill="")+
  scale_fill_manual(values=cb)

# MeHg
gg2<-ggplot(water.all.MeHg, aes(x=ID, y=MeHg.water.ng.L,  fill=Site.type))+
  geom_bar(stat="identity")+
  theme_bw()+

  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="none",
        axis.title = element_blank())+
  scale_fill_manual(values=cb)+
  labs(fill="")

## Percent MeHg
gg3<-ggplot(water.all.Percent, aes(x=ID, y=Percent.MeHg.water, fill=Site.type))+
  geom_bar(stat="identity")+
  theme_bw()+
  #labs(x="\nIndividual Samples",fill="")+
  labs(x = 'Muestras Individuales') +
  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="none",
        axis.title.y = element_blank())+
  scale_fill_manual(values=cb)

## Sediment THg
gg4<-ggplot(water.all.THg.sed, aes(x=ID,y=Ave.THg.sed.ug.g,fill=Site.type))+
  geom_bar(stat="identity")+
  theme_bw()+
  #labs(x="Individual Samples",y="")+
  labs(x = 'Muestras Individuales', y = '') +
  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank())+
  labs (fill="\ncount")+scale_fill_manual (values=cb)

## Sediment THg
gg5<-ggplot(water.all.THg.TSS, aes(x=ID,y=TSS.mg.L,fill=Site.type))+
  geom_bar(stat="identity")+
  theme_bw()+
  #labs(x="Individual Samples",y="") +
  labs(x = 'Muestras Individuales', y = '') +
  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank())+
  labs(fill="\ncount")+scale_fill_manual(values=cb)


#Combine plots into a water column figure and sediment figure

#Water column figure
lg <- ggpubr::get_legend(g4)
g <- ggpubr::ggarrange(g1,gg1,g2,gg2,g3,gg3,nrow=3,ncol=2,common.legend=TRUE,legend.grob = lg)
g

ggsave('figures/Spanish/HgAnalysis.png', plot = g, width = 7, units = 'in', dpi = 600)

#Sediment figure
ggpubr::ggarrange(g4,gg4,nrow=1,ncol=2,common.legend=TRUE, legend.grob = lg)

ggsave('figures/Spanish/HgSed.png', width = 7, height = 3.5, units = 'in', dpi = 600)

##TSS Figure
ggpubr::ggarrange(g5,gg5,nrow=1,ncol=2,common.legend=TRUE, legend.grob = lg)

ggsave('figures/Spanish/HgTSS.png', width = 7, height = 3.5, units = 'in', dpi = 600)
##Water.all and tss mg/L column same as gg4 but with TSS
```



```{r cars}
## Take a look at distributions and run some statistics

#Calculate summary statistics for Hg concentrations in water
water.all %>%  
  group_by(Site.type) %>% 
  summarize(n=n(),
            mean_THg = mean(THg.water.ng.L, na.rm = TRUE),
            sd_THg=sd(THg.water.ng.L, na.rm = TRUE),
            mean_MeHg=mean(MeHg.water.ng.L,na.rm=TRUE),
            sd_MeHg=sd(MeHg.water.ng.L, na.rm = TRUE),
            mean_Percent=mean(Percent.MeHg.water,na.rm=T),
            sd_Percent=sd(Percent.MeHg.water, na.rm = TRUE))

#Compare THg concentrations in water by surface water type

shapiro.test(residuals(object =aov(THg.water.ng.L~Site.type,data=water.all)  ))
# p<0.05-data are not normally distributed
kruskal.test(THg.water.ng.L ~ Site.type, data = water.all)
FSA::dunnTest(THg.water.ng.L ~ Site.type, data = water.all)

#Compare MeHg concentrations in water by surface water type
shapiro.test(residuals(object =aov(MeHg.water.ng.L~Site.type,data=water.all)  ))
# p<0.05-data are not normally distributed
kruskal.test(MeHg.water.ng.L ~ Site.type, data = water.all)
FSA::dunnTest(MeHg.water.ng.L ~ Site.type, data = water.all)

#Compare %MeHg concentrations in water by surface water type
shapiro.test(residuals(object =aov(Percent.MeHg.water~Site.type,data=water.all)  ))
# p<0.05-data are not normally distributed
kruskal.test(Percent.MeHg.water ~ Site.type, data = water.all)
FSA::dunnTest(Percent.MeHg.water ~ Site.type, data = water.all)

#Compare THg concentrations in sediment by surface water type
shapiro.test(residuals(object =aov(Ave.THg.sed.ug.g~Site.type,data=water.all)  ))
# p<0.05-data are not normally distributed
kruskal.test(Ave.THg.sed.ug.g ~ Site.type, data = water.all)
FSA::dunnTest(Ave.THg.sed.ug.g ~ Site.type, data = water.all)

#Compare TSS concentrations by surface water type
shapiro.test(residuals(object =aov(TSS.mg.L~Site.type,data=water.all)  ))
#p<0.05-data are not normally distributed
kruskal.test(TSS.mg.L ~ Site.type, data = water.all)
FSA::dunnTest(TSS.mg.L ~ Site.type, data = water.all)

#Compare sediment %C  by surface water type
shapiro.test(residuals(object =aov(Percent.C.sed~Site.type,data=water.all)  ))
#p<0.05-data are not normally distributed
kruskal.test(Percent.C.sed ~ Site.type, data = water.all)
FSA::dunnTest(Percent.C.sed ~ Site.type, data = water.all)

#TSS vs. THg
p1 <- ggplot(water.all, aes(x=TSS.mg.L, y=THg.water.ng.L))+
  geom_point(size=2.5,alpha=.7, aes(color=Site.type))+
  #labs(y="THg (ng/L)",x="Total Suspended Solids (mg/L)",color="") +
  labs(y="HgT (ng/L)",x="Sólidos Suspendidos Totales (mg/L)",color="") +
  scale_color_manual(values=cb, labels = fig.labels) +
  scale_x_continuous(trans = 'log10') +
  scale_y_continuous(trans = 'log10') +
  ggpmisc::stat_fit_glance(method = 'lm',
                           label.y = 'top',
                           label.x = 'middle',
                           method.args = list(formula = y ~ x),
                           mapping = aes(label = sprintf('R^2~"="~%.3f~~italic(P)~"="~%.2g',
                                stat(r.squared), stat(p.value))),
                  parse = TRUE) +
    theme_bw() +
  theme(legend.position = 'top')

## TSS vs MeHg
p2 <- ggplot(water.all, aes(x=TSS.mg.L, y=MeHg.water.ng.L))+
  geom_point(size=2.5,alpha=.7, aes(color = Site.type))+
  #labs(y="MeHg (ng/L)",x="Total Suspended Solids (mg/L)",color="") +
  labs(y="MeHg (ng/L)",x="Sólidos Suspendidos Totales (mg/L)",color="") +
  scale_color_manual(values=cb) +
  scale_x_continuous(trans = 'log10') +
  scale_y_continuous(trans = 'log10') +
  ggpmisc::stat_fit_glance(method = 'lm',
                           label.y = 'top',
                           label.x = 'middle',
                           method.args = list(formula = y ~ x),
                           mapping = aes(label = sprintf('R^2~"="~%.3f~~italic(P)~"="~%.2g',
                                stat(r.squared), stat(p.value))),
                  parse = TRUE) +
    theme_bw()

lg <- ggpubr::get_legend(p1)
g <- ggpubr::ggarrange(p1, p2,nrow=1,ncol=2, common.legend=TRUE, legend.grob = lg)
g

ggsave('figures/Spanish/TSSvTHgvMeHgLog.png', plot = g, width = 7, height = 3, units = 'in', dpi = 600)

## Look at R2 and regression results
summary(lm(data=water.all,THg.water.ng.L~TSS.mg.L))

```


## Redo figure 3 normalized by TSS

```{r cars}
#Create boxplots to compare Hg concentrations across surface water types
cb <- c("#56B4E9","#E69F00","#999999","#0072B2","#D55E00")

water.all.norm <- water.all %>%
  mutate(THg.water.ng.L = THg.water.ng.L/TSS.mg.L,
         MeHg.water.ng.L = MeHg.water.ng.L/TSS.mg.L,
         Percent.MeHg.water = Percent.MeHg.water/TSS.mg.L)

## Total Hg
kruskal.test(THg.water.ng.L ~ Site.type, data = water.all.norm)
FSA::dunnTest(THg.water.ng.L ~ Site.type, data = water.all.norm)
print(FSA::dunnTest(THg.water.ng.L ~ Site.type, data = water.all.norm), dunn.test.results = T)

tukeyThg <- tibble(Site.type = c('River Upstream', 'Oxbow Upstream', 'Mining Pond', 'River Downstream', 'Oxbow Downstream'), TukeyStats = c('a','a','ab','a','a'))

g1<-ggplot(water.all.norm,aes(x=Site.type, y=THg.water.ng.L)) + 
  geom_boxplot(aes(fill=Site.type)) +
  geom_label(data = tukeyThg, aes(y = Inf, label = TukeyStats), vjust = 2, label.size = .2) +
  labs(x="",y="THg/TSS\n(ng/mg)") + 
  scale_y_continuous(trans = 'log10') +
  theme_bw() + 
  theme(axis.text.x=element_blank(),
        legend.position="top") + 
  scale_fill_manual(values=cb) + 
  labs(fill="") 


## MeHg
kruskal.test(MeHg.water.ng.L ~ Site.type, data = water.all.norm)
FSA::dunnTest(MeHg.water.ng.L~ Site.type, data = water.all.norm)
print(FSA::dunnTest(MeHg.water.ng.L ~ Site.type, data = water.all.norm), dunn.test.results = T)

tukeyMeHg <- tibble(Site.type = water.labels, TukeyStats = c('a','a','a','ab','a'))
  
g2<-ggplot(water.all.norm,aes(x=Site.type, y=MeHg.water.ng.L)) + 
  geom_boxplot(aes(fill=Site.type)) +
  geom_label(data = tukeyMeHg, aes(y = Inf, label = TukeyStats), vjust = 2, label.size = .2) +
  scale_y_continuous(trans = 'log10') +
  theme_bw()+
  labs(y="MeHg/TSS\n(ng/mg)")+
  theme(axis.text.x=element_blank(),
        legend.position="none") +
  scale_fill_manual(values=cb)



#Create frequency distributions to compare Hg concentrations across surface water types
water.all.norm.THg<-water.all.norm[order(-water.all.norm$THg.water.ng.L),]
water.all.norm.THg$ID<-seq.int(nrow(water.all.norm.THg))
water.all.norm.MeHg<-water.all.norm[order(-water.all.norm$MeHg.water.ng.L),]
water.all.norm.MeHg$ID<-seq.int(nrow(water.all.norm.MeHg))
water.all.norm.Percent<-water.all.norm[order(-water.all.norm$Percent.MeHg.water),]
water.all.norm.Percent$ID<-seq.int(nrow(water.all.norm.Percent))
water.all.norm.THg.sed<-water.all.norm[order(-water.all.norm$Ave.THg.sed.ug.g),]
water.all.norm.THg.sed$ID<-seq.int(nrow(water.all.norm.THg.sed))
water.all.norm.THg.TSS<-water.all.norm[order(-water.all.norm$TSS.mg.L),]
water.all.norm.THg.TSS$ID<-seq.int(nrow(water.all.norm.THg.TSS))

#Total Hg
gg1<-ggplot(water.all.norm.THg, aes(x=ID, y=THg.water.ng.L, fill=Site.type))+
  geom_bar(stat="identity")+
  theme_bw()+labs(x="",y="")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="none")+
  labs(fill="")+
  scale_fill_manual(values=cb)

# MeHg
gg2<-ggplot(water.all.norm.MeHg, aes(x=ID, y=MeHg.water.ng.L,  fill=Site.type))+
  geom_bar(stat="identity")+
  theme_bw()+
  labs(x="",y="")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="none")+
  scale_fill_manual(values=cb)+
  labs(fill="")

#Combine plots into a water column figure and sediment figure

#Water column figure
g <- ggpubr::ggarrange(g1,gg1,g2,gg2,nrow=2,ncol=2,common.legend=TRUE)
g
ggsave('figures/Final/HgAnalysisTSSNorm.png', plot = g, width = 7, units = 'in', dpi = 600)
```


